import type { Company } from '../_lib/types'

export const COMPANIES: Company[] = [
  {
    logo: 'N',
    name: 'Northwind Design',
    role: 'Senior Product Designer · Remote',
    status: 'interview',
    statusLabel: 'Interview',
    emails: 5,
    last: 'Interview Tue at 2 PM',
    when: '2h ago',
  },
  {
    logo: '✦',
    name: 'Fieldnote',
    role: 'Design Engineer · NYC',
    status: 'offer',
    statusLabel: 'Offer',
    emails: 8,
    last: 'Decision by May 3',
    when: 'Sat',
  },
  {
    logo: '◎',
    name: 'Lumen Labs',
    role: 'Product Manager, Growth · Austin',
    status: 'replied',
    statusLabel: 'Recruiter replied',
    emails: 3,
    last: 'Waiting on scope',
    when: 'Apr 18',
  },
  {
    logo: 'T',
    name: 'Thorne & Co',
    role: 'Staff Designer · Remote',
    status: 'interview',
    statusLabel: 'Intro scheduled',
    emails: 4,
    last: 'Intro w/ Elena, Thu',
    when: 'Apr 12',
  },
  {
    logo: 'A',
    name: 'Anvil',
    role: 'Design Lead · SF',
    status: 'interview',
    statusLabel: 'Take-home',
    emails: 2,
    last: 'Due Friday',
    when: 'Apr 10',
  },
  {
    logo: 'H',
    name: 'Harbor',
    role: 'Senior UX Researcher · Remote',
    status: 'applied',
    statusLabel: 'Applied',
    emails: 1,
    last: 'Auto-confirmation',
    when: 'Apr 16',
  },
  {
    logo: 'K',
    name: 'Kindle & Co',
    role: 'Senior Designer · Remote',
    status: 'replied',
    statusLabel: 'Referred',
    emails: 2,
    last: 'Waiting on hiring team',
    when: 'Apr 07',
  },
  {
    logo: 'R',
    name: 'Relay',
    role: 'Product Designer II · Remote',
    status: 'rejected',
    statusLabel: 'Closed',
    emails: 6,
    last: 'Not moving forward',
    when: 'Apr 15',
  },
  {
    logo: 'M',
    name: 'Meridian',
    role: 'Design Director · Remote',
    status: 'final',
    statusLabel: 'Final round',
    emails: 11,
    last: 'Panel Apr 25',
    when: 'Apr 13',
  },
  {
    logo: 'V',
    name: 'Vellum',
    role: 'Senior Designer · Remote',
    status: 'applied',
    statusLabel: 'Applied',
    emails: 1,
    last: 'No reply yet',
    when: 'Apr 05',
  },
]
